version: "3"

services:
  rmis:
    build: ./rmis
    container_name: rmis-app
    ports:
      - "8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  db:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

volumes:
  mongodbdata:

networks:
  app-network:  # fixed name here
