spring.application.name=RetailManagementInventorySystem
server.port= 7070
# Default admin credentials (override in production)
app.admin.email=rmisindustries@company.com
app.admin.password=admin123
spring.data.mongodb.uri= mongodb://localhost:27017/retail_management_db

